name: example_json
description: An example on how to use `package:messages`.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  intl4x: ^0.7.0
  messages: ^0.2.0

dev_dependencies:
  build_daemon: ^4.0.0
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  dart_flutter_team_lints: ^1.0.0
  lints: ^2.0.0
  messages_builder: ^0.2.0
  path: ^1.8.3
  test: ^1.16.0

package_options:
  messages_builder:
    generateMethods: true
    generateFindById: false
    generateFindBy: integer
    pluralSelector: intl4x
