name: example_json
description: An example on how to use `package:messages`.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  messages:
    path: ../

dev_dependencies:
  build_daemon: ^4.0.0
  build_runner: ^2.3.3
  build_web_compilers: ^4.0.5
  dart_flutter_team_lints: ^1.0.0
  lints: ^2.0.0
  messages_builder:
    path: ../../messages_builder
  path: ^1.8.3
  test: ^1.16.0

messages:
  generateMethods: true
  generateFindById: false
  generateFindBy: none
  useCleaner: false
  async: true
