# Configuration for .github/workflows/pull_request_label.yml. 

'infra':
  - '.github/**'

'pkg:intl':
  - 'pkgs/intl/**'

'pkg:intl_translation':
  - 'pkgs/intl_translation/**'

'pkg:messages':
  - 'pkgs/messages/**'

'pkg:messages_builder':
  - 'pkgs/messages_builder/**'

'pkg:messages_serializer':
  - 'pkgs/messages_serializer/**'

'pkg:messages_shrinker':
  - 'pkgs/messages_shrinker/**'