# Configuration for .github/workflows/pull_request_label.yml. 

'infra':
  - '.github/**'

'pkg:intl':
  - 'pkgs/intl/**'

'pkg:intl_translation':
  - 'pkgs/intl_translation/**'

'pkg:intl4x':
  - 'pkgs/intl4x/**'
