# Configuration for .github/workflows/pull_request_label.yml. 

'type-infra':
  - '.github/**'

'package:intl':
  - 'pkgs/intl/**'

'package:intl_translation':
  - 'pkgs/intl_translation/**'

'package:intl4x':
  - 'pkgs/intl4x/**'

'package:messages':
  - 'pkgs/messages/**'

'package:messages_serializer':
  - 'pkgs/messages_serializer/**'

'package:messages_deserializer':
  - 'pkgs/messages_deserializer/**'

'package:messages_builder':
  - 'pkgs/messages_builder/**'

'package:messages_shrinker':
  - 'pkgs/messages_shrinker/**'
