# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  copyBuilder:
    import: "package:messages_builder/builder.dart"
    builder_factories: ["messagesBuilder"]
    build_extensions: {'.arb': ['.g.dart', '.json'], '^pubspec.yaml': []}
    build_to: source
    auto_apply: root_package