name: messages_builder
description: Build the messages for consumption by package:messages
version: 0.1.0
publish_to: none
repository: https://github.com/dart-lang/i18n/pkgs/messages_builder

environment:
  sdk: ^3.0.0

dependencies:
  build: ^2.3.1
  code_builder: ^4.3.0
  collection: ^1.18.0
  crypto: ^3.0.3
  dart_style: ^2.2.4
  glob: ^2.1.1
  intl: ^0.18.0
  messages:
    git:
      url: git@github.com:dart-lang/i18n.git
      path: pkgs/messages
  messages_serializer:
    git:
      url: git@github.com:dart-lang/i18n.git
      path: pkgs/messages_serializer
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^4.0.5
  dart_flutter_team_lints: ^1.0.0
  lints: ^2.0.0
  messages_deserializer:
    git:
      url: git@github.com:dart-lang/i18n.git
      path: pkgs/messages_deserializer
  test: ^1.16.0
