name: example_web
description: An example on how to use the intl4x package.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.19.0
  js: ^0.6.7

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.9
  dart_flutter_team_lints: ^2.1.1
  lints: ^3.0.0
