name: messages_shrinker
description: A starting point for Dart libraries or applications.
version: 0.1.0
publish_to: none
repository: https://github.com/dart-lang/i18n/pkgs/messages_shrinker

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  analyzer: ^6.2.0
  args: ^2.4.2
  build: ^2.4.1
  messages: ^0.1.0
  messages_builder: ^0.1.0
  messages_deserializer: ^0.1.0
  messages_serializer: ^0.1.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  lints: ^2.0.0
  test: ^1.21.0
