name: messages_shrinker
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
repository: https://github.com/dart-lang/i18n/

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  messages:
    path: ../messages
  messages_builder:
    path: ../messages_builder
  messages_serializer:
    path: ../messages_serializer
  messages_deserializer:
    path: ../messages_deserializer
  analyzer: ^6.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
