name: messages_shrinker
description: A starting point for Dart libraries or applications.
version: 0.0.1-dev
publish_to: none
repository: https://github.com/dart-lang/i18n/tree/main/pkgs/messages_shrinker

environment:
  sdk: '>=2.18.0 <3.0.0'

# Add regular dependencies here.
dependencies:
  messages:
    path: ../messages
  messages_builder:
    path: ../messages_builder
  messages_serializer:
    path: ../messages_serializer

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
