name: messages
description: Localize your application
version: 1.0.0
publish_to: none
repository: https://github.com/dart-lang/i18n/tree/main/pkgs/messages

environment:
  sdk: ^3.0.0

dependencies:
  intl: ^0.18.0
  messages_deserializer:
    path: ../messages_deserializer
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
