name: messages_deserializer
description: Deserialization of messages for package:messages.
version: 0.1.0
repository: https://github.com/dart-lang/i18n/tree/main/pkgs/messages_deserializer

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  js: ^0.6.5
  messages: ^0.1.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  lints: ^3.0.0
  test: ^1.21.0
