name: messages_serializer
description: A starting point for Dart libraries or applications.
version: 0.0.1-dev
publish_to: none
repository: https://github.com/dart-lang/i18n/tree/main/pkgs/messages_serializer

environment:
  sdk: '>=3.0.0-163.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  messages:
    path: ../messages
  code_builder: ^4.3.0
  dart_style: ^2.2.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
