name: Unicode Conformance Testing
on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/conformance.yml'
      - 'pkgs/intl4x/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/conformance.yml'
      - 'pkgs/intl4x/**'
  schedule:
    - cron: '0 0 * * *' # daily
    
jobs:
    run_all:
      runs-on: ubuntu-latest
      steps:
        - uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
          with:
            sdk: stable

        - uses: actions/checkout@7739b9ba2efcda9dde65ad1e3c2dbe65b41dfba7
                
        - uses: actions/checkout@7739b9ba2efcda9dde65ad1e3c2dbe65b41dfba7
          with:
            repository: unicode-org/conformance
            path: 'conformance'
        
        - run: mv pkgs/intl4x/test/tools/conformance_config.json conformance/conformance_config.json

        - run: (cd conformance; bash generateDataAndRun.sh conformance_config.json)

        - name: Download Reference Exec Summary
          if: github.ref != 'refs/heads/main'
          continue-on-error: true
          uses: actions/download-artifact@e9ef242655d12993efdcda9058dee2db83a2cb9b
          with:
            name: reference_exec_summary

        - run: (cd pkgs/intl4x; dart pub get)
          if: github.ref != 'refs/heads/main'

        - run: dart run pkgs/intl4x/test/tools/conformance_parser.dart --current-path conformance/TEMP_DATA/testReports/exec_summary.json --reference-path reference_exec_summary >> $GITHUB_STEP_SUMMARY
          if: github.ref != 'refs/heads/main'

        - name: Upload Reference Summary iff on main branch
          if: github.ref == 'refs/heads/main'
          uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
          with:
            name: reference_exec_summary
            path: conformance/TEMP_DATA/testReports/exec_summary.json
