name: package:intl_translation
permissions: read-all

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/intl_translation.yml'
      - 'pkgs/intl_translation/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/intl_translation.yml'
      - 'pkgs/intl_translation/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkgs/intl_translation
    strategy:
      matrix:
        sdk: [stable, dev] # {pkgs.versions}
        include:
          - sdk: stable
            run-tests: true
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: ${{matrix.sdk}}

      - run: dart pub get

      - run: dart analyze --fatal-infos

      # Note that the files in example/lib/generated aren't formatted.
      - run: dart format --output=none --set-exit-if-changed bin lib
        if: ${{matrix.run-tests}}

      - run: dart test
        if: ${{matrix.run-tests}}
