name: package:intl4x
permissions: read-all

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/intl4x.yml'
      - 'pkgs/intl4x/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/intl4x.yml'
      - 'pkgs/intl4x/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ICU4X_BUILD_MODE: fetch
    
    defaults:
      run:
        working-directory: pkgs/intl4x
    strategy:
      matrix:
        sdk: [stable, dev] # {pkgs.versions}
        include:
          - sdk: stable
            run-tests: true
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          submodules: true

      - uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: ${{matrix.sdk}}

      - run: dart --enable-experiment=native-assets pub get

      - run: dart --enable-experiment=native-assets analyze --fatal-infos

      - run: dart --enable-experiment=native-assets format --output=none --set-exit-if-changed .
        if: ${{matrix.run-tests}}

      - run: dart --enable-experiment=native-assets test
        if: ${{matrix.run-tests}}

      - run: dart --enable-experiment=native-assets test -p chrome
        if: ${{matrix.run-tests}}
