include: package:dart_flutter_team_lints/analysis_options.yaml

linter:
  rules:
    prefer_relative_imports: True
    prefer_const_constructors: True
    unnecessary_parenthesis: True
    conditional_uri_does_not_exist: True