name: intl4x
description: >-
  A lightweight modular library for internationalization (i18n) functionality.
version: 0.5.0
repository: https://github.com/dart-lang/i18n/tree/main/pkgs/intl4x

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  js: ^0.6.5
  
dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  dart_flutter_team_lints: ^1.0.0
  lints: ^2.0.0
  test: ^1.22.1
